import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

let outputChannel: vscode.OutputChannel;

export function activate(context: vscode.ExtensionContext) {
    outputChannel = vscode.window.createOutputChannel('Rust Pattern Viz');
    outputChannel.appendLine('Rust Pattern Visualizer extension activated');

    // Register hover provider for Rust files
    const hoverProvider = vscode.languages.registerHoverProvider('rust', {
        provideHover(document, position, token) {
            return providePatternHover(document, position);
        }
    });

    // Register command to generate diagram for current file
    const generateCommand = vscode.commands.registerCommand(
        'rustPatternViz.generateDiagram',
        async () => {
            const editor = vscode.window.activeTextEditor;
            if (!editor || editor.document.languageId !== 'rust') {
                vscode.window.showWarningMessage('Please open a Rust file first');
                return;
            }

            await generateAndShowDiagram(editor.document);
        }
    );

    // Register settings command
    const settingsCommand = vscode.commands.registerCommand(
        'rustPatternViz.openSettings',
        () => {
            vscode.commands.executeCommand('workbench.action.openSettings', 'rustPatternViz');
        }
    );

    context.subscriptions.push(hoverProvider, generateCommand, settingsCommand, outputChannel);

    // Show welcome message for beta
    vscode.window.showInformationMessage(
        'Rust Pattern Viz (Beta): Hover over functions to see pattern diagrams. Pro version with enhanced features coming soon!',
        'Learn More'
    ).then(selection => {
        if (selection === 'Learn More') {
            vscode.env.openExternal(vscode.Uri.parse('https://github.com/yourusername/rust-pattern-viz'));
        }
    });
}

async function providePatternHover(
    document: vscode.TextDocument,
    position: vscode.Position
): Promise<vscode.Hover | null> {
    const config = vscode.workspace.getConfiguration('rustPatternViz');
    
    if (!config.get<boolean>('enableHover', true)) {
        return null;
    }

    // Check if we're hovering over a function, impl, or struct keyword
    const line = document.lineAt(position.line);
    const text = line.text;
    
    const relevantKeywords = ['fn ', 'impl ', 'struct ', 'enum ', 'trait '];
    const isRelevant = relevantKeywords.some(kw => text.includes(kw));
    
    if (!isRelevant) {
        return null;
    }

    try {
        const cliPath = await findCliPath(config);
        const filePath = document.uri.fsPath;
        
        outputChannel.appendLine(`Analyzing ${filePath} at line ${position.line + 1}`);

        // Generate SVG diagram using CLI
        const svgContent = await generateSvgDiagram(cliPath, filePath);
        
        if (!svgContent) {
            return null;
        }

        // Encode SVG as base64 for embedding in Markdown
        const base64Svg = Buffer.from(svgContent).toString('base64');
        const imageUri = `data:image/svg+xml;base64,${base64Svg}`;

        const markdown = new vscode.MarkdownString();
        markdown.isTrusted = true;
        markdown.supportHtml = true;

        markdown.appendMarkdown(`### 🦀 Pattern Analysis\n\n`);
        markdown.appendMarkdown(`![Pattern Diagram](${imageUri})\n\n`);
        markdown.appendMarkdown(`---\n\n`);
        markdown.appendMarkdown(`*Generated by Rust Pattern Viz* | `);
        markdown.appendMarkdown(`[⚙️ Settings](command:rustPatternViz.openSettings) | `);
        markdown.appendMarkdown(`[📊 Full Diagram](command:rustPatternViz.generateDiagram)\n\n`);
        markdown.appendMarkdown(`**🎯 Pro Version Coming Soon**: Enhanced diagrams, real-time updates, and team collaboration features`);

        return new vscode.Hover(markdown);

    } catch (error) {
        outputChannel.appendLine(`Error generating hover: ${error}`);
        return null;
    }
}

async function generateAndShowDiagram(document: vscode.TextDocument): Promise<void> {
    const config = vscode.workspace.getConfiguration('rustPatternViz');
    
    try {
        const cliPath = await findCliPath(config);
        const filePath = document.uri.fsPath;
        
        vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: "Generating pattern diagram...",
            cancellable: false
        }, async (progress) => {
            const svgContent = await generateSvgDiagram(cliPath, filePath);
            
            if (!svgContent) {
                vscode.window.showErrorMessage('Failed to generate diagram');
                return;
            }

            // Save SVG to temp file and open
            const outputPath = path.join(
                path.dirname(filePath),
                `${path.basename(filePath, '.rs')}_pattern_diagram.svg`
            );
            
            fs.writeFileSync(outputPath, svgContent);
            
            const doc = await vscode.workspace.openTextDocument(outputPath);
            await vscode.window.showTextDocument(doc, vscode.ViewColumn.Beside);
            
            vscode.window.showInformationMessage(
                `Diagram saved to ${path.basename(outputPath)}`,
                'Open in Browser'
            ).then(selection => {
                if (selection === 'Open in Browser') {
                    vscode.env.openExternal(vscode.Uri.file(outputPath));
                }
            });
        });

    } catch (error) {
        vscode.window.showErrorMessage(`Error: ${error}`);
        outputChannel.appendLine(`Error: ${error}`);
    }
}

async function findCliPath(config: vscode.WorkspaceConfiguration): Promise<string> {
    // 1. Check user configuration
    const configuredPath = config.get<string>('cliPath');
    if (configuredPath && fs.existsSync(configuredPath)) {
        return configuredPath;
    }

    // 2. Check workspace debug build
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (workspaceFolders && workspaceFolders.length > 0) {
        const workspaceRoot = workspaceFolders[0].uri.fsPath;
        const debugPath = path.join(workspaceRoot, 'target', 'debug', 'rpv');
        const releasePath = path.join(workspaceRoot, 'target', 'release', 'rpv');
        
        if (fs.existsSync(releasePath)) {
            return releasePath;
        }
        if (fs.existsSync(debugPath)) {
            return debugPath;
        }
    }

    // 3. Check system PATH
    try {
        const { stdout } = await execAsync(process.platform === 'win32' ? 'where rpv' : 'which rpv');
        const systemPath = stdout.trim().split('\n')[0];
        if (systemPath && fs.existsSync(systemPath)) {
            return systemPath;
        }
    } catch {
        // Command failed, rpv not in PATH
    }

    // 4. Not found - show helpful error
    throw new Error(
        'rpv CLI tool not found. Please:\n' +
        '1. Build the project: cargo build --release\n' +
        '2. Or configure the path in settings: rustPatternViz.cliPath\n' +
        '3. Or install globally: cargo install --path .'
    );
}

async function generateSvgDiagram(cliPath: string, filePath: string): Promise<string | null> {
    const config = vscode.workspace.getConfiguration('rustPatternViz');
    const maxSize = config.get<number>('maxDiagramSize', 5000);

    try {
        const { stdout, stderr } = await execAsync(
            `"${cliPath}" analyze "${filePath}" --output-format svg`,
            { maxBuffer: maxSize * 1024 }
        );

        if (stderr) {
            outputChannel.appendLine(`CLI stderr: ${stderr}`);
        }

        if (!stdout || stdout.trim().length === 0) {
            outputChannel.appendLine('CLI returned empty output');
            return null;
        }

        // Validate SVG output
        if (!stdout.includes('<svg') || !stdout.includes('</svg>')) {
            outputChannel.appendLine('CLI output is not valid SVG');
            return null;
        }

        return stdout;

    } catch (error: any) {
        outputChannel.appendLine(`CLI execution error: ${error.message}`);
        
        if (error.code === 'ENOENT') {
            vscode.window.showErrorMessage(
                'rpv CLI not found. Please build the project or configure the path in settings.',
                'Open Settings'
            ).then(selection => {
                if (selection === 'Open Settings') {
                    vscode.commands.executeCommand('rustPatternViz.openSettings');
                }
            });
        }
        
        return null;
    }
}

export function deactivate() {
    if (outputChannel) {
        outputChannel.dispose();
    }
}
